version: '3'

services:
  hydra:
    image: oryd/hydra:v1.0.0-beta.9
    ports:
      - 4444:4444
      - 4445:4445
    environment:
      DATABASE_URL: memory
    command:
      serve all --dangerous-force-http

  keto:
    image: oryd/keto
    ports:
      - 4466:4466
    environment:
      DATABASE_URL: memory
    command: serve

  # oathkeeper-proxy:
  #   image: oryd/oathkeeper
  #   ports:
  #     - 4455:4455
  #   environment:
  #     CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM: ory-hydra
  #     CREDENTIALS_ISSUER_ID_TOKEN_ISSUER: http://oathkeeper-api:4456
  #     DATABASE_URL: memory
  #   command:
  #     serve proxy

  # oathkeeper-api:
  #   image: oryd/oathkeeper
  #   ports:
  #     - 4456:4456
  #   environment:
  #     CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM: ory-hydra
  #     CREDENTIALS_ISSUER_ID_TOKEN_ISSUER: http://oathkeeper-api:4456
  #     DATABASE_URL: memory
  #   command:
  #     serve api
