version: '2'

services:
  hydra:
    image: oryd/hydra:v1.0.0-beta.9
    ports:
      - 4444:4444
      - 4445:4445
    environment:
      DATABASE_URL: memory
    command:
      serve all --dangerous-force-http

  keto:
    image: oryd/keto
    ports:
      - 4466:4466
    environment:
      DATABASE_URL: memory
    command: serve

  oathkeeper-proxy:
    image: oryd/oathkeeper
    ports:
      - 4455:4455
    depends_on:
      - oathkeeper-api
      - hydra
      - keto
    environment:
      AUTHENTICATOR_ANONYMOUS_USERNAME: anonymous
      AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL: http://hydra:4444/oauth2/token
      AUTHENTICATOR_OAUTH2_INTROSPECTION_URL: http://hydra:4445/oauth2/introspect
      AUTHORIZER_KETO_WARDEN_KETO_URL: http://keto:4466
      CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM: ory-hydra
      CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL: http://hydra:4445
      CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID: resources:hydra:jwk:oathkeeper
      CREDENTIALS_ISSUER_ID_TOKEN_ISSUER: http://oathkeeper-api:4456
      DATABASE_URL: memory
      OATHKEEPER_API_URL: http://oathkeeper-api:4456
      PORT: 4455
    command:
      serve proxy

  oathkeeper-api:
    image: oryd/oathkeeper
    ports:
      - 4456:4456
    environment:
      AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL: http://hydra:4444/oauth2/token
      AUTHENTICATOR_OAUTH2_INTROSPECTION_URL: http://hydra:4445/oauth2/introspect
      AUTHORIZER_KETO_WARDEN_KETO_URL: http://keto:4466
      CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM: ory-hydra
      CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM: ory-hydra
      CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL: http://hydra:4445
      CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID: resources:hydra:jwk:oathkeeper
      CREDENTIALS_ISSUER_ID_TOKEN_ISSUER: http://oathkeeper-api:4456
      CREDENTIALS_ISSUER_ID_TOKEN_ISSUER: http://oathkeeper-api:4456
      DATABASE_URL: memory
      PORT: 4456
    command:
      serve api
